name: Build Wadai Hj. Party APK
on:
  push:
    branches: [ "UAS-Mobile" ]
    workflows_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build debug APK with Gradle
        run: ./gradlew assembleDebug
      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: WadaiHjParty-debug-apk
          paths: app/build/outputs/apk/debug/app-debug.apk
